### ISSUE TITLE
`parse` return value

### ISSUE THREAD

**Issue by mindrunner** [lukeed/ms#3]
Is there any specific reason for `parse` returning `number | void`? Wouldn't `number | undefined` be more natural?

**Comment by lukeed** [comment]
They’re the same thing. There’s only a slight difference in TS semantics, but effectively (and actually) are identical

**Comment by mindrunner** [comment]
> They’re the same thing

They are not. `undefined` describes non-existence whereas `void` describes the unknown of existence. I have never seen `void` being used as an optional return type, hence my question.

Returning `number | undefined` would for example allow to directly assign the return value to an optional variable, whereas `number | void` forces me to explicitly check for what was returned.

Not a big deal, I was just wondering what your intention might have been.

**Comment by lukeed** [comment]
This [explanation](https://stackoverflow.com/questions/58885485/why-does-typescript-have-both-void-and-undefined) convinced me. I'll update it
